// Code generated by protoc-gen-gogo.
// source: autonat.proto
// DO NOT EDIT!

/*
Package autonat_pb is a generated protocol buffer package.

It is generated from these files:
	autonat.proto

It has these top-level messages:
	Message
*/
package autonat_pb

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

type Message_MessageType int32

const (
	Message_DIAL          Message_MessageType = 0
	Message_DIAL_RESPONSE Message_MessageType = 1
)

var Message_MessageType_name = map[int32]string{
	0: "DIAL",
	1: "DIAL_RESPONSE",
}
var Message_MessageType_value = map[string]int32{
	"DIAL":          0,
	"DIAL_RESPONSE": 1,
}

func (x Message_MessageType) Enum() *Message_MessageType {
	p := new(Message_MessageType)
	*p = x
	return p
}
func (x Message_MessageType) String() string {
	return proto.EnumName(Message_MessageType_name, int32(x))
}
func (x *Message_MessageType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_MessageType_value, data, "Message_MessageType")
	if err != nil {
		return err
	}
	*x = Message_MessageType(value)
	return nil
}

type Message_ResponseStatus int32

const (
	Message_OK               Message_ResponseStatus = 0
	Message_E_DIAL_ERROR     Message_ResponseStatus = 100
	Message_E_DIAL_REFUSED   Message_ResponseStatus = 101
	Message_E_INTERNAL_ERROR Message_ResponseStatus = 200
)

var Message_ResponseStatus_name = map[int32]string{
	0:   "OK",
	100: "E_DIAL_ERROR",
	101: "E_DIAL_REFUSED",
	200: "E_INTERNAL_ERROR",
}
var Message_ResponseStatus_value = map[string]int32{
	"OK":               0,
	"E_DIAL_ERROR":     100,
	"E_DIAL_REFUSED":   101,
	"E_INTERNAL_ERROR": 200,
}

func (x Message_ResponseStatus) Enum() *Message_ResponseStatus {
	p := new(Message_ResponseStatus)
	*p = x
	return p
}
func (x Message_ResponseStatus) String() string {
	return proto.EnumName(Message_ResponseStatus_name, int32(x))
}
func (x *Message_ResponseStatus) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(Message_ResponseStatus_value, data, "Message_ResponseStatus")
	if err != nil {
		return err
	}
	*x = Message_ResponseStatus(value)
	return nil
}

type Message struct {
	Type             *Message_MessageType  `protobuf:"varint,1,opt,name=type,enum=autonat.pb.Message_MessageType" json:"type,omitempty"`
	Dial             *Message_Dial         `protobuf:"bytes,2,opt,name=dial" json:"dial,omitempty"`
	DialResponse     *Message_DialResponse `protobuf:"bytes,3,opt,name=dialResponse" json:"dialResponse,omitempty"`
	XXX_unrecognized []byte                `json:"-"`
}

func (m *Message) Reset()         { *m = Message{} }
func (m *Message) String() string { return proto.CompactTextString(m) }
func (*Message) ProtoMessage()    {}

func (m *Message) GetType() Message_MessageType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return Message_DIAL
}

func (m *Message) GetDial() *Message_Dial {
	if m != nil {
		return m.Dial
	}
	return nil
}

func (m *Message) GetDialResponse() *Message_DialResponse {
	if m != nil {
		return m.DialResponse
	}
	return nil
}

type Message_PeerInfo struct {
	Id               []byte   `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Addrs            [][]byte `protobuf:"bytes,2,rep,name=addrs" json:"addrs,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *Message_PeerInfo) Reset()         { *m = Message_PeerInfo{} }
func (m *Message_PeerInfo) String() string { return proto.CompactTextString(m) }
func (*Message_PeerInfo) ProtoMessage()    {}

func (m *Message_PeerInfo) GetId() []byte {
	if m != nil {
		return m.Id
	}
	return nil
}

func (m *Message_PeerInfo) GetAddrs() [][]byte {
	if m != nil {
		return m.Addrs
	}
	return nil
}

type Message_Dial struct {
	Peer             *Message_PeerInfo `protobuf:"bytes,1,opt,name=peer" json:"peer,omitempty"`
	XXX_unrecognized []byte            `json:"-"`
}

func (m *Message_Dial) Reset()         { *m = Message_Dial{} }
func (m *Message_Dial) String() string { return proto.CompactTextString(m) }
func (*Message_Dial) ProtoMessage()    {}

func (m *Message_Dial) GetPeer() *Message_PeerInfo {
	if m != nil {
		return m.Peer
	}
	return nil
}

type Message_DialResponse struct {
	Status           *Message_ResponseStatus `protobuf:"varint,1,opt,name=status,enum=autonat.pb.Message_ResponseStatus" json:"status,omitempty"`
	StatusText       *string                 `protobuf:"bytes,2,opt,name=statusText" json:"statusText,omitempty"`
	Addr             []byte                  `protobuf:"bytes,3,opt,name=addr" json:"addr,omitempty"`
	XXX_unrecognized []byte                  `json:"-"`
}

func (m *Message_DialResponse) Reset()         { *m = Message_DialResponse{} }
func (m *Message_DialResponse) String() string { return proto.CompactTextString(m) }
func (*Message_DialResponse) ProtoMessage()    {}

func (m *Message_DialResponse) GetStatus() Message_ResponseStatus {
	if m != nil && m.Status != nil {
		return *m.Status
	}
	return Message_OK
}

func (m *Message_DialResponse) GetStatusText() string {
	if m != nil && m.StatusText != nil {
		return *m.StatusText
	}
	return ""
}

func (m *Message_DialResponse) GetAddr() []byte {
	if m != nil {
		return m.Addr
	}
	return nil
}

func init() {
	proto.RegisterType((*Message)(nil), "autonat.pb.Message")
	proto.RegisterType((*Message_PeerInfo)(nil), "autonat.pb.Message.PeerInfo")
	proto.RegisterType((*Message_Dial)(nil), "autonat.pb.Message.Dial")
	proto.RegisterType((*Message_DialResponse)(nil), "autonat.pb.Message.DialResponse")
	proto.RegisterEnum("autonat.pb.Message_MessageType", Message_MessageType_name, Message_MessageType_value)
	proto.RegisterEnum("autonat.pb.Message_ResponseStatus", Message_ResponseStatus_name, Message_ResponseStatus_value)
}
